'use client'

import { CheckCircle2, Award, Users, Target } from 'lucide-react'

export default function About() {
  const highlights=[{icon:Award,title:'Expertise Comprovada',description:'Atuação dedicada ao direito empresarial e à consultoria jurídica.'},{icon:Users,title:'Equipe Dedicada',description:'Profissionais qualificados e comprometidos com excelência no atendimento.'},{icon:Target,title:'Foco em Resultados',description:'Soluções personalizadas que atendem às necessidades específicas de cada cliente.'}]
  return <section id="sobre" className="section-padding bg-gray-50"><div className="container-custom">
    <div className="max-w-3xl mx-auto text-center mb-16 animate-fadeIn"><span className="text-accent-500 font-semibold text-lg">SOBRE NÓS</span><h2 className="mt-4 mb-6 text-primary-900">Advocacia de Qualidade e Confiança</h2><p className="text-lg text-gray-600">O Escritório Danilo Freire Advogados é referência em consultoria jurídica empresarial, oferecendo soluções jurídicas inovadoras e personalizadas para empresas e profissionais.</p></div>
    <div className="grid grid-cols-1 lg:grid-cols-2 gap-12 items-center mb-16"><div className="space-y-6 animate-slideInLeft">{highlights.map((item,index)=>{const Icon=item.icon;return <div key={index} className="flex gap-4 p-6 bg-white rounded-xl border border-gray-200 hover:border-accent-400 hover:shadow-lg transition-all duration-300"><div className="flex-shrink-0"><Icon className="w-8 h-8 text-accent-500"/></div><div><h3 className="font-bold text-primary-900 mb-2">{item.title}</h3><p className="text-gray-600">{item.description}</p></div></div>})}</div>
    <div className="space-y-8 animate-slideUp"><div><h3 className="text-2xl font-bold text-primary-900 mb-4">Nossos Valores</h3><p className="text-gray-600 mb-6">Acreditamos que a excelência em advocacia vai além do conhecimento técnico. Comprometemo-nos com integridade, transparência e dedicação às causas de nossos clientes.</p></div><div className="space-y-4">{['Integridade Profissional','Confidencialidade Total','Atendimento Personalizado','Agilidade nas Soluções'].map((value,index)=><div key={index} className="flex items-center gap-3"><CheckCircle2 className="w-6 h-6 text-accent-500 flex-shrink-0"/><span className="text-gray-700 font-medium">{value}</span></div>)}</div><div className="bg-gradient-to-r from-primary-50 to-accent-50 p-6 rounded-xl border border-accent-200"><p className="text-primary-900 italic">"Nosso compromisso é transformar desafios jurídicos em oportunidades de sucesso para nossos clientes."</p></div></div></div>
    <div className="bg-primary-900 text-white rounded-2xl p-10 md:p-12 animate-slideUp"><div className="max-w-3xl mx-auto text-center"><p className="text-accent-400 font-semibold tracking-wide uppercase text-sm mb-3">Atendimento personalizado</p><h3 className="text-3xl md:text-4xl font-bold mb-4">Clareza jurídica para decisões mais seguras.</h3><p className="text-gray-300 text-lg mb-7">Converse com o escritório e apresente sua necessidade. A primeira conversa é o ponto de partida para entender o melhor caminho.</p><a href="#contato" className="btn-secondary">Falar com o escritório</a></div></div>
  </div></section>
}